services:
  # image service
  image-service:
    build: ./image-service
    hostname: image-service
    environment:
      DB_URL: mongodb://node:node@imagedb:27017?authSource=admin
      DB_NAME: image
      JWT_ISSUER: authservice
    depends_on:
      - image-service-db
  # image service database (MongoDB)
  image-service-db:
    image: mongo
    hostname: imagedb
    environment:
      MONGO_INITDB_ROOT_USERNAME: node
      MONGO_INITDB_ROOT_PASSWORD: node
      MONGO_INITDB_DATABASE: image
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      retries: 5
      interval: 15s
      start_period: 30s
  # gateway service
  gateway-service:
    build: ./gateway-service
    ports:
      - "8080:8080"
  # auth service
  auth-service:
    build: ./auth-service
    hostname: auth-service
    environment:
      DB_HOST: authdb
      DB_PORT: 5432
      DB_USER: node
      DB_PASSWORD: password
      DB_NAME: node
    depends_on:
      - auth-service-db
  # auth service database (PostgreSQL)
  auth-service-db:
    image: postgres
    hostname: authdb
    environment:
      POSTGRES_USER: node
      POSTGRES_PASSWORD: node
      POSTGRES_DB: node
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U node" ]
      interval: 5s
      timeout: 5s
      retries: 5
  # location service
  location-service:
    build: ./location-service
    hostname: location-service
    environment:
      DB_URL: mongodb://node:node@locationdb:27017?authSource=admin
      DB_NAME: location
    depends_on:
      - location-service-db
  # location service database (MongoDB)
  location-service-db:
    image: mongo
    hostname: locationdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: node
      MONGO_INITDB_ROOT_PASSWORD: node
      MONGO_INITDB_DATABASE: location
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      retries: 5
      interval: 15s
      start_period: 30s
  # MongoDB database seeding
  mongo-seed:
    image: mongo
    volumes:
      - ./initdb:/initdb
    command:
      - /initdb/initmongo.sh